### PR TITLE
remove IntelliJ / Android Studio files configuration files

### PR DESCRIPTION
**Pull request by alorma**
With this files, i need to remove manually and then load the APp in Android studio.

Removing them, make it easy, just import the project :D

[Review on Reviewable](https://reviewable.io/reviews/andrew-quebe/planets-gradle/5)

### CODE REVIEW

**Comment by Andrew-Quebe** [comment]
I don't see why you need to remove the specified files. On my end, my project compiles fine with them. I'd check your configuration of Android Studio first. You shouldn't have to remove files to import into AS.

**Comment by Andrew-Quebe** [comment]
Also, may I ask why you'd like to import the project?

**Comment by alorma** [comment]
In your side it compiles.

But in .iml files are locations from your system, that can cause problems to other devs.

I want to make some material improvements

**Comment by Andrew-Quebe** [comment]
Alright...I'll give it a try.

**Comment by Andrew-Quebe** [comment]
@alorma I just compiled your changes and it still ended up generating the files you said to remove. I've reverted your PR because I don't see how it changed anything. Perhaps you could update the .gitignore so it won't upload those files?

**Comment by Andrew-Quebe** [comment]
In fact, it seems the .gitignore already has that so I don't know what your issue is...like I said, check your AS config.

**Comment by alorma** [comment]
The files were in the repository, maybe because a first upload.

I just removed them from repository.

If `.gitignore ` works, files will never be uploaded again

**Pull request merged**
